#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export recursive=0
export dry_run=0
export confirm=1

while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            echo "asciify-names [-r|--resursive] [--dry-run] [--no-interactive] [--] [files ...]"
            exit
            ;;
        -r|--recursive)
            recursive=1
            shift
            ;;
         --dry-run)
            dry_run=1
            shift
            ;;
        --no-interactive)
            confirm=0
            shift
            ;;
         --)
            shift
            break
            ;;
         *)
            break
            ;;
    esac
done

if [[ $# == 0 ]]; then
    echo "No files specified!"
    exit 1
fi

paths=("$@")

tmpdir="$(mktemp -d)"
original_paths="$tmpdir/original_paths"
original_names="$tmpdir/original_names"
ascii_names="$tmpdir/ascii_names"

if [[ $recursive == 1 ]]; then
    find "${paths[@]}" -depth -print0
else
    printf '%s\0' "$@"
fi >"$original_paths"

while IFS='' read -d '' -r file; do
    printf "%s\0" "${file##*/}"
done <"$original_paths" >"$original_names"

asciify <"$original_names" | tr '/' '_' >"$ascii_names"

exec {original_paths_fd}<"$original_paths"
exec {ascii_names_fd}<"$ascii_names"

while IFS='' read -d '' -r file <&$original_paths_fd &&
      IFS='' read -d '' -r asciiname <&$ascii_names_fd; do
    name="${file##*/}"
    dir="${file::-${#name}}"
    
    if [[ "$name" != "$asciiname" ]]; then
        old_path="$dir$name"
        new_path="$dir$asciiname"

        if [[ $dry_run == 1 ]]; then
            echo  "Would rename: $old_path --> $new_path"
        else
            echo  "Renaming: $old_path --> $new_path"
            if [[ $confirm == 1 ]]; then
                mv -i "$old_path" "$new_path"
            else
                mv "$old_path" "$new_path"
            fi
        fi
    fi
done

rm -r "$tmpdir"
