#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export recursive=0
export dry_run=0
export confirm=1

while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            echo "asciify-names [-r|--resursive] [--dry-run] [--no-interactive] [--] [files ...]"
            exit
            ;;
        -r|--recursive)
            recursive=1
            shift
            ;;
         --dry-run)
            dry_run=1
            shift
            ;;
        --no-interactive)
            confirm=0
            shift
            ;;
         --)
            shift
            break
            ;;
         *)
            break
            ;;
    esac
done

if [[ $# == 0 ]]; then
    echo "No files specified!"
    exit 1
fi

paths=("$@")

tmpdir="$(mktemp -d)"
export fifo_in="$tmpdir/fifo_in"
export fifo_out="$tmpdir/fifo_out"
mkfifo "$fifo_in"
mkfifo "$fifo_out"

asciify <"$fifo_in" >"$fifo_out" &

if [[ $recursive == 1 ]]; then
    find "${paths[@]}" -depth
else
    for file in "$@"; do
        printf '%s\n' "$file"
    done
fi | {
    exec {in}> "$fifo_in"

    while IFS='' read -r file; do
        basename "$file" >&$in &
        printf "%s\n" "$file"
        wait
    done
} | {
    exec {out}< "$fifo_out"

    while IFS='' read -r file &&
          IFS='' read -r asciiname <&$out ; do
        dir="$(dirname "$file")"
        name="$(basename "$file")"
        
        if [[ "$name" != "$asciiname" ]]; then
            old_path="$dir/$name"
            new_path="$dir/$asciiname"

            if [[ $dry_run == 1 ]]; then
                echo  "Would rename: $old_path --> $new_path"
            else
                echo  "Renaming: $old_path --> $new_path"
                if [[ $confirm == 1 ]]; then
                    mv -i "$old_path" "$new_path" </dev/tty
                else
                    mv "$old_path" "$new_path"
                fi
            fi
        fi
    done
}

rm -r "$tmpdir"
